# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Repositories\Cpp-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Repositories\Cpp-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Repositories\Cpp-project\CMakeFiles C:\Repositories\Cpp-project\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Repositories\Cpp-project\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RewardSystemApp

# Build rule for target.
RewardSystemApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 RewardSystemApp
.PHONY : RewardSystemApp

# fast build rule for target.
RewardSystemApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/build
.PHONY : RewardSystemApp/fast

source/main.obj: source/main.cpp.obj
.PHONY : source/main.obj

# target to build an object file
source/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/main.cpp.obj
.PHONY : source/main.cpp.obj

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/models/Transaction.obj: source/models/Transaction.cpp.obj
.PHONY : source/models/Transaction.obj

# target to build an object file
source/models/Transaction.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/Transaction.cpp.obj
.PHONY : source/models/Transaction.cpp.obj

source/models/Transaction.i: source/models/Transaction.cpp.i
.PHONY : source/models/Transaction.i

# target to preprocess a source file
source/models/Transaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/Transaction.cpp.i
.PHONY : source/models/Transaction.cpp.i

source/models/Transaction.s: source/models/Transaction.cpp.s
.PHONY : source/models/Transaction.s

# target to generate assembly for a file
source/models/Transaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/Transaction.cpp.s
.PHONY : source/models/Transaction.cpp.s

source/models/User.obj: source/models/User.cpp.obj
.PHONY : source/models/User.obj

# target to build an object file
source/models/User.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/User.cpp.obj
.PHONY : source/models/User.cpp.obj

source/models/User.i: source/models/User.cpp.i
.PHONY : source/models/User.i

# target to preprocess a source file
source/models/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/User.cpp.i
.PHONY : source/models/User.cpp.i

source/models/User.s: source/models/User.cpp.s
.PHONY : source/models/User.s

# target to generate assembly for a file
source/models/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/User.cpp.s
.PHONY : source/models/User.cpp.s

source/models/Wallet.obj: source/models/Wallet.cpp.obj
.PHONY : source/models/Wallet.obj

# target to build an object file
source/models/Wallet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/Wallet.cpp.obj
.PHONY : source/models/Wallet.cpp.obj

source/models/Wallet.i: source/models/Wallet.cpp.i
.PHONY : source/models/Wallet.i

# target to preprocess a source file
source/models/Wallet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/Wallet.cpp.i
.PHONY : source/models/Wallet.cpp.i

source/models/Wallet.s: source/models/Wallet.cpp.s
.PHONY : source/models/Wallet.s

# target to generate assembly for a file
source/models/Wallet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/models/Wallet.cpp.s
.PHONY : source/models/Wallet.cpp.s

source/services/AdminService.obj: source/services/AdminService.cpp.obj
.PHONY : source/services/AdminService.obj

# target to build an object file
source/services/AdminService.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/AdminService.cpp.obj
.PHONY : source/services/AdminService.cpp.obj

source/services/AdminService.i: source/services/AdminService.cpp.i
.PHONY : source/services/AdminService.i

# target to preprocess a source file
source/services/AdminService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/AdminService.cpp.i
.PHONY : source/services/AdminService.cpp.i

source/services/AdminService.s: source/services/AdminService.cpp.s
.PHONY : source/services/AdminService.s

# target to generate assembly for a file
source/services/AdminService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/AdminService.cpp.s
.PHONY : source/services/AdminService.cpp.s

source/services/AuthService.obj: source/services/AuthService.cpp.obj
.PHONY : source/services/AuthService.obj

# target to build an object file
source/services/AuthService.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/AuthService.cpp.obj
.PHONY : source/services/AuthService.cpp.obj

source/services/AuthService.i: source/services/AuthService.cpp.i
.PHONY : source/services/AuthService.i

# target to preprocess a source file
source/services/AuthService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/AuthService.cpp.i
.PHONY : source/services/AuthService.cpp.i

source/services/AuthService.s: source/services/AuthService.cpp.s
.PHONY : source/services/AuthService.s

# target to generate assembly for a file
source/services/AuthService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/AuthService.cpp.s
.PHONY : source/services/AuthService.cpp.s

source/services/OTPService.obj: source/services/OTPService.cpp.obj
.PHONY : source/services/OTPService.obj

# target to build an object file
source/services/OTPService.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/OTPService.cpp.obj
.PHONY : source/services/OTPService.cpp.obj

source/services/OTPService.i: source/services/OTPService.cpp.i
.PHONY : source/services/OTPService.i

# target to preprocess a source file
source/services/OTPService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/OTPService.cpp.i
.PHONY : source/services/OTPService.cpp.i

source/services/OTPService.s: source/services/OTPService.cpp.s
.PHONY : source/services/OTPService.s

# target to generate assembly for a file
source/services/OTPService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/OTPService.cpp.s
.PHONY : source/services/OTPService.cpp.s

source/services/UserService.obj: source/services/UserService.cpp.obj
.PHONY : source/services/UserService.obj

# target to build an object file
source/services/UserService.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/UserService.cpp.obj
.PHONY : source/services/UserService.cpp.obj

source/services/UserService.i: source/services/UserService.cpp.i
.PHONY : source/services/UserService.i

# target to preprocess a source file
source/services/UserService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/UserService.cpp.i
.PHONY : source/services/UserService.cpp.i

source/services/UserService.s: source/services/UserService.cpp.s
.PHONY : source/services/UserService.s

# target to generate assembly for a file
source/services/UserService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/UserService.cpp.s
.PHONY : source/services/UserService.cpp.s

source/services/WalletService.obj: source/services/WalletService.cpp.obj
.PHONY : source/services/WalletService.obj

# target to build an object file
source/services/WalletService.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/WalletService.cpp.obj
.PHONY : source/services/WalletService.cpp.obj

source/services/WalletService.i: source/services/WalletService.cpp.i
.PHONY : source/services/WalletService.i

# target to preprocess a source file
source/services/WalletService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/WalletService.cpp.i
.PHONY : source/services/WalletService.cpp.i

source/services/WalletService.s: source/services/WalletService.cpp.s
.PHONY : source/services/WalletService.s

# target to generate assembly for a file
source/services/WalletService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/services/WalletService.cpp.s
.PHONY : source/services/WalletService.cpp.s

source/utils/FileHandler.obj: source/utils/FileHandler.cpp.obj
.PHONY : source/utils/FileHandler.obj

# target to build an object file
source/utils/FileHandler.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/FileHandler.cpp.obj
.PHONY : source/utils/FileHandler.cpp.obj

source/utils/FileHandler.i: source/utils/FileHandler.cpp.i
.PHONY : source/utils/FileHandler.i

# target to preprocess a source file
source/utils/FileHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/FileHandler.cpp.i
.PHONY : source/utils/FileHandler.cpp.i

source/utils/FileHandler.s: source/utils/FileHandler.cpp.s
.PHONY : source/utils/FileHandler.s

# target to generate assembly for a file
source/utils/FileHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/FileHandler.cpp.s
.PHONY : source/utils/FileHandler.cpp.s

source/utils/HashUtils.obj: source/utils/HashUtils.cpp.obj
.PHONY : source/utils/HashUtils.obj

# target to build an object file
source/utils/HashUtils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/HashUtils.cpp.obj
.PHONY : source/utils/HashUtils.cpp.obj

source/utils/HashUtils.i: source/utils/HashUtils.cpp.i
.PHONY : source/utils/HashUtils.i

# target to preprocess a source file
source/utils/HashUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/HashUtils.cpp.i
.PHONY : source/utils/HashUtils.cpp.i

source/utils/HashUtils.s: source/utils/HashUtils.cpp.s
.PHONY : source/utils/HashUtils.s

# target to generate assembly for a file
source/utils/HashUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/HashUtils.cpp.s
.PHONY : source/utils/HashUtils.cpp.s

source/utils/InputValidator.obj: source/utils/InputValidator.cpp.obj
.PHONY : source/utils/InputValidator.obj

# target to build an object file
source/utils/InputValidator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/InputValidator.cpp.obj
.PHONY : source/utils/InputValidator.cpp.obj

source/utils/InputValidator.i: source/utils/InputValidator.cpp.i
.PHONY : source/utils/InputValidator.i

# target to preprocess a source file
source/utils/InputValidator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/InputValidator.cpp.i
.PHONY : source/utils/InputValidator.cpp.i

source/utils/InputValidator.s: source/utils/InputValidator.cpp.s
.PHONY : source/utils/InputValidator.s

# target to generate assembly for a file
source/utils/InputValidator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/InputValidator.cpp.s
.PHONY : source/utils/InputValidator.cpp.s

source/utils/Logger.obj: source/utils/Logger.cpp.obj
.PHONY : source/utils/Logger.obj

# target to build an object file
source/utils/Logger.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/Logger.cpp.obj
.PHONY : source/utils/Logger.cpp.obj

source/utils/Logger.i: source/utils/Logger.cpp.i
.PHONY : source/utils/Logger.i

# target to preprocess a source file
source/utils/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/Logger.cpp.i
.PHONY : source/utils/Logger.cpp.i

source/utils/Logger.s: source/utils/Logger.cpp.s
.PHONY : source/utils/Logger.s

# target to generate assembly for a file
source/utils/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/Logger.cpp.s
.PHONY : source/utils/Logger.cpp.s

source/utils/TimeUtils.obj: source/utils/TimeUtils.cpp.obj
.PHONY : source/utils/TimeUtils.obj

# target to build an object file
source/utils/TimeUtils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/TimeUtils.cpp.obj
.PHONY : source/utils/TimeUtils.cpp.obj

source/utils/TimeUtils.i: source/utils/TimeUtils.cpp.i
.PHONY : source/utils/TimeUtils.i

# target to preprocess a source file
source/utils/TimeUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/TimeUtils.cpp.i
.PHONY : source/utils/TimeUtils.cpp.i

source/utils/TimeUtils.s: source/utils/TimeUtils.cpp.s
.PHONY : source/utils/TimeUtils.s

# target to generate assembly for a file
source/utils/TimeUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RewardSystemApp.dir\build.make CMakeFiles/RewardSystemApp.dir/source/utils/TimeUtils.cpp.s
.PHONY : source/utils/TimeUtils.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... RewardSystemApp
	@echo ... source/main.obj
	@echo ... source/main.i
	@echo ... source/main.s
	@echo ... source/models/Transaction.obj
	@echo ... source/models/Transaction.i
	@echo ... source/models/Transaction.s
	@echo ... source/models/User.obj
	@echo ... source/models/User.i
	@echo ... source/models/User.s
	@echo ... source/models/Wallet.obj
	@echo ... source/models/Wallet.i
	@echo ... source/models/Wallet.s
	@echo ... source/services/AdminService.obj
	@echo ... source/services/AdminService.i
	@echo ... source/services/AdminService.s
	@echo ... source/services/AuthService.obj
	@echo ... source/services/AuthService.i
	@echo ... source/services/AuthService.s
	@echo ... source/services/OTPService.obj
	@echo ... source/services/OTPService.i
	@echo ... source/services/OTPService.s
	@echo ... source/services/UserService.obj
	@echo ... source/services/UserService.i
	@echo ... source/services/UserService.s
	@echo ... source/services/WalletService.obj
	@echo ... source/services/WalletService.i
	@echo ... source/services/WalletService.s
	@echo ... source/utils/FileHandler.obj
	@echo ... source/utils/FileHandler.i
	@echo ... source/utils/FileHandler.s
	@echo ... source/utils/HashUtils.obj
	@echo ... source/utils/HashUtils.i
	@echo ... source/utils/HashUtils.s
	@echo ... source/utils/InputValidator.obj
	@echo ... source/utils/InputValidator.i
	@echo ... source/utils/InputValidator.s
	@echo ... source/utils/Logger.obj
	@echo ... source/utils/Logger.i
	@echo ... source/utils/Logger.s
	@echo ... source/utils/TimeUtils.obj
	@echo ... source/utils/TimeUtils.i
	@echo ... source/utils/TimeUtils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

